### PR TITLE
[squash me] private / protected / public

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@athanatos Hi Sam, just found that your branch did not build. so i am creating this PR to address it. i think it's very likely that it's just your local branch is not sync'ed with the remote one... anyway, HTH.

**Comment by athanatos** [comment]
I don't seem to need this to build.  Cache is a friend class to CachedExtent, and the two set_ methods aren't used outside of FixedKVNodeLayout by design.  Can you elaborate on the build error you saw?

**Comment by tchaikov** [comment]
```
In file included from ../src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc:11:
../src/crimson/os/seastore/lba_manager/btree/lba_btree_node_impl.h: In member function ‘virtual void crimson::os::seastore::lba_manager::btree::LBAInternalNode::apply_delta(crimson::os::seastore::paddr_t\
, const bufferlist&)’:
../src/crimson/os/seastore/lba_manager/btree/lba_btree_node_impl.h:183:5: error: ‘uint32_t crimson::os::seastore::CachedExtent::last_committed_crc’ is private within this context
  183 |     last_committed_crc = get_crc32c();
      |     ^~~~~~~~~~~~~~~~~~
In file included from ../src/crimson/os/seastore/cache.h:14,
                 from ../src/crimson/os/seastore/lba_manager.h:20,
                 from ../src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h:19,
                 from ../src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc:10:
../src/crimson/os/seastore/cached_extent.h:51:12: note: declared private here
   51 |   uint32_t last_committed_crc = 0;
      |            ^~~~~~~~~~~~~~~~~~
In file included from ../src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc:11:
../src/crimson/os/seastore/lba_manager/btree/lba_btree_node_impl.h: In member function ‘virtual void crimson::os::seastore::lba_manager::btree::LBALeafNode::apply_delta(crimson::os::seastore::paddr_t, co\
nst bufferlist&)’:
../src/crimson/os/seastore/lba_manager/btree/lba_btree_node_impl.h:396:5: error: ‘uint32_t crimson::os::seastore::CachedExtent::last_committed_crc’ is private within this context
  396 |     last_committed_crc = get_crc32c();
      |     ^~~~~~~~~~~~~~~~~~
In file included from ../src/crimson/os/seastore/cache.h:14,
                 from ../src/crimson/os/seastore/lba_manager.h:20,
                 from ../src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h:19,
                 from ../src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.cc:10:
../src/crimson/os/seastore/cached_extent.h:51:12: note: declared private here
   51 |   uint32_t last_committed_crc = 0;
      |            ^~~~~~~~~~~~~~~~~~
```

**Comment by tchaikov** [comment]
see https://paste.centos.org/view/44453819 for the full error output.

**Comment by athanatos** [comment]
Ah, got it.  I pushed a somewhat different change, thanks!

**Pull request closed without merging**
